### PR TITLE
Add Mac Instructions on Making Auto-DNS Work

### PR DESCRIPTION
**Pull request by xmarkclx**
# Add Mac Instructions on Making Auto-DNS Work

#### Short description

Added Mac Instructions on Making Auto-DNS Work

#### Tasks done

* [ ] Updated `Configure.md`

### CODE REVIEW

**Comment by cytopia** [comment]
Thanks for the support.

**Comment by tsouhaieb** [comment]
instruction about mac dns config not working

**Comment by cytopia** [comment]
@tsouhaieb 

The documentation has been highly updated since that time. Can you see if the new documentation makes it work for you: http://devilbox.readthedocs.io/en/latest/configuration-global/auto-dns.html


Alternatively, can you also try out this PR: https://github.com/cytopia/devilbox/pull/138 (Branch `DVL-013-fix-dns`). Might still be something that is left to be merged in case of OSX

**Comment by tsouhaieb** [comment]
@cytopia  i already checked the url above and i applied all the instuction but problem still persist for auto dns (manually work properly), i will give branch `DVL-013-fix-dns` a try, thanks anyway for this great project

**Comment by tsouhaieb** [comment]
@cytopia i used the branch `DVL-013-fix-dns` and still does not work, thanks anyway

**Comment by cytopia** [comment]
@tsouhaieb feel free to open up a separate issue and I can try to get it working for you.

**Comment by tsouhaieb** [comment]
@cytopia thinks for the reply, to make it work, i needed to explicitly write `LOCAL_LISTEN_ADDR=127.0.0.1:`,  `LOCAL_LISTEN_ADDR=` do not work for me,

**Pull request merged**
