### PR TITLE
Release v1.8.0

### PR DESCRIPTION
**Pull request by cytopia**
# Release v1.8.0

#### Fixed
- [#739](https://github.com/cytopia/devilbox/issues/739) Disabled gd-jis: https://bugs.php.net/bug.php?id=73582
- [#740](https://github.com/cytopia/devilbox/issues/740) Use latest PHP 8.0 image

#### Added
- [#715](https://github.com/cytopia/devilbox/issues/715) PHP module mongodb is re-added to PHP 8.0
- Added **PHP 8.1**: https://github.com/devilbox/docker-php-fpm-8.1
- Added Postgres images: 11.7, 11.8, 11.9, 12.2, 12.3, 12.4, 13.0
- Added Redis images: 6.0
- Added Memcache images: 1.6
- Added MongoDB images: 4.4
- Added MySQL images: MariaDB 10.5

#### Changed
- [#736](https://github.com/cytopia/devilbox/issues/736) Composer is updated to v2 (`/usr/local/bin/composer`)
- [#728](https://github.com/cytopia/devilbox/issues/728) Updated phpPgAdmin from 7.12 to 7.13
- Updated phpMyAdmin from 5.0.0 to 5.0.4
- Updated phpMyAdmin from 4.9.3 to 4.9.7
- Updated Adminer from 4.7.5 to 4.7.7
- Composer is available as v1 and v2 (`/usr/local/bin/composer-1` and `/usr/local/bin/composer-2`)
- New default PHP version: 7.4
- New default MySQL version: MariaDB 10.5
- New default Postgres version: 12.4
- New default Redis version: 6.0
- New default Memcached version 1.6
- New default MongoDB version: 4.4

### CODE REVIEW

**Comment by warmwhisky** [comment]
I think I am missing something here. When I run `composer -v` I get `bash: /bin/composer: No such file or directory`

I tried installing composer with `yum install composer` but it only pulls in composer 1.10 and somehow php 5.3.

Is there another way to use composer 2 that is installed when using devil box. I am using ` Devilbox v1.9.0 (2020-12-12) `

**Comment by warmwhisky** [comment]
Ok I got it. I first run `sudo ./shell.sh` then cd to `/shared/httpd/mydomain` and it worked. Thanks.
I've just installed this on a Centos dev box at work to test response times compared to my dev box at home which is very slow.

Have been using it on Linux Mint for the last week at home. Everything works fine with the exception of crazy response times (anything from 6 to 30 seconds) when viewing any page with mysql calls. Cannot understand it, but must be something already on Linux Mint that is causing it as I was getting exactly the same 20 second response times using XAMPP. Thing is when I use the same app on my Centos server in production the response is 3 to 4 seconds. This is a page that has 900 queries running! I know its a lot of queries, but the page itself is essential.

I also have a Windows 7 Devbox at work running XAMPP with HTTPS HTTP2 and that is running super quick. 3 seconds to load the heavy page with 900 queries.

I've been struggling with Linux Mint/XAMPP for 2 months now. Crazy response times are driving me crazy and all searches for solutions are now melting into one great big confusing nightmare! 

I wonder if you have any clue to why linux mint would have such terrible response times with both XAMPP and Devilbox?

**Comment by cytopia** [comment]
> Ok I got it. I first run `sudo ./shell.sh`

FYI: The `sudo` part should not be necessary, also especially when starting the docker containers.

**Comment by warmwhisky** [comment]
Would you have any idea why my response times are crazy long?

I have finally got this working on the Centos devbox at work and the response times are now 45 seconds. I am so lost on what I can do to make this work.

Currently tested on...
Linux Mint (local)  - Devilbox 1.8 Nginx, PHP 7.4 (tried(7.3) - response time **6 to 30 seconds**
Centos 7 (local)  - Devilbox 1.9 Nginx, PHP 7.4 - response times so far always **45 - 46 seconds.**
Windows 7 (local) - XAMMP Apache 2.4, PHP 7.3  - response time - **3.6 seconds**
Centos 7 (Production) WHM (Easy Apache 4), Apache 2.4, PHP 7.3 - response time - **3.6 seconds**

**Comment by cytopia** [comment]
This I also don't know. In order to speed things up you could do the following:

* Disable unwanted modules (especially xdebug): `PHP_MODULES_DISABLE=oci8,PDO_OCI,pdo_sqlsrv,sqlsrv,rdkafka,swoole,xdebug` (<- and what else you don't need)
* Use a different mount option, e.g.: `MOUNT_OPTIONS=,cached` within `.env`

**Comment by warmwhisky** [comment]
I get the following error when appending cached like this `MOUNT_OPTIONS=,cached` 
`Error for devilbox_php_1 Cannot create container for service php: invalid bind mount spec "devilbox_devilbox-mail:/var/mail:rw,cached": invalid mode: rw,cache`

and

`MOUNT_OPTIONS=,z,cached`
`Error for devilbox_php_1 Cannot create container for service php: invalid bind mount spec "/home/username/devilbox/mod/php-fpm-7.4:/usr/lib64/php/custom-modules:ro,z,cached": invalid mode: ro,z,cache`

**Pull request merged**
