### PR TITLE
Add How To for ExpressionEngine cms

### PR DESCRIPTION
**Pull request by ops-andy**
# Add How To for ExpressionEngine cms

### Goal

To add installation instructions for installing ExpressionEngine in devilbox.

Have instructions added to docs

### DESCRIPTION

I've added instructions for installing ExpressionEngine cms. I also added appropriate links and added to FAQ.

I must admit that I could not get any preview tools to render the docs. However, I've gone over the commit pretty thoroughly and believe that all the syntax is correct.

### CODE REVIEW

**Comment by cytopia** [comment]
> I must admit that I could not get any preview tools to render the docs. However, I've gone over the commit pretty thoroughly and believe that all the syntax is correct.

FYI: You can go into the `docs/` directory and type `make autobuild`. This will start a dockerized sphinx server (no dependencies required) and make a live preview available on port 8000 which can be viewed in your browser.

**Comment by ops-andy** [comment]
ah. that's a lot easier than trying to get this running before. I already see another syntax error that I'll resolve and push. I'll wait on this local build to complete and then push any other errors I find. 
Thanks!

**Comment by cytopia** [comment]
> ah. that's a lot easier than trying to get this running before. I already see another syntax error that I'll resolve and push. I'll wait on this local build to complete and then push any other errors I find.
> Thanks!

`make build` will also tell you syntax errors. This is also being run in CI to catch them: https://github.com/cytopia/devilbox/pull/686/checks?check_run_id=519819535

**Comment by ops-andy** [comment]
> > ah. that's a lot easier than trying to get this running before. I already see another syntax error that I'll resolve and push. I'll wait on this local build to complete and then push any other errors I find.
> > Thanks!
> 
> `make build` will also tell you syntax errors. This is also being run in CI to catch them: https://github.com/cytopia/devilbox/pull/686/checks?check_run_id=519819535

I've pushed what I believe to be final updates (under my other username :/ ). I was able to build the docs with no errors locally. Also checked over everything and made a few more corrections to the doc.  Looks like all the tests on here are queued. Do I need to do anything to have those run again?

**Pull request merged**
