### PR TITLE
Use alpine images

### PR DESCRIPTION
**Pull request by cytopia**
# ~~Use Alpine based images~~
# Allow to freely choose images

#### DESCRIPTION

~~This PR replaces official Docker images with Alpine versions where available.~~
This PR updates all official Docker image versions and allows the user to choose Alpine or Debian where available.

* ~~Use smaller Alpine based images~~
* Enable optional use of Alpine based images
* Add TravisCI checks against all provided images

### CODE REVIEW

**Comment by normance** [comment]
I don't know if it is still accurate but some discussions point risks for OSX or Windows of Alpine images :
https://blog.codeship.com/alpine-based-docker-images-make-difference-real-world-apps/

The catch is that Alpine does not use GNU's libc, being this the main cause of its small size. Alternative libc implementation usually works, however, they are not the usual development environment, neither usually the fastest. There's some risk involved (probably small).

It's worth noting that if you're using the Docker Toolbox on OSX or Windows you may run into file syncing issues with Alpine based images. Here's an issue that goes into that in more detail: https://disq.us/url?url=https%3A%2F%2Fgithub.com%2Fdocker%2Ftoolbox%2Fissues%2F510%3AoHzP8ddIQ0aApEe0jURqQFqpbCM&cuid=922894

**Comment by cytopia** [comment]
@normance that's actually a very good argument. I've checked and the issue is still open. I will revert explicit Alpine images and leave it open to the user by adding a comment to `env-example`.

**Comment by hetykai** [comment]
I think it may be better to comment out the Alpine configuration and let the user choose, rather than delete it.
And I think the users generally does not modify the files mounted by the database images outside the container, so in general it does not encounter that issue.

**Comment by cytopia** [comment]
@normance  @hetykai The compromise now is to add both (Alpine and Debian based images) as commented choice to `env-example` and also to do TravisCI checks against both. Additionally there's a note including a link to the above issue on every `XXX_SERVER` define that offers Alpine based images in the `env-example` file.

**Pull request merged**
