### PR TITLE
Release v1.0.0: Docker volumes (breaking changes)

### PR DESCRIPTION
**Pull request by cytopia**
# Docker volumes

### READFIRST

This branch is constantly being rebased from `master` until final merge, therefore requires git force pushing. Keep this in mind when checking it out via git.

### Feedback

To move on faster and pain-free, please try out this branch and provide your Feedback. I will update the description correspondingly.

* [x] Tested on Linux
* [x] Tested on Windows (native)
* [x] Tested on MacOS (native)
* [x] Tested on Windows (Docker Toolbox)
* [ ] Tested on MacOS (Docker Toolbox)

Also ensure the following has been done:

* [ ] Ensure that named volumes have their own configuration for mount options (similar to `MOUNT_OPTIONS`)

### Notes on this PR

This PR will be merged into `release/v1.0.0`

### DESCRIPTION

This PR will move all data directories (MySQL, PostgreSQL, MongoDB and others) to Docker volumes for best-practice and compatibility reasons on different operating systems.

This is mainly a huge step for Windows user as they seem to have issues with current Docker mounts over and over again. However it should also generally increase performance for all other systems.

### IMPORTANT

When using this branch, you will loose all you current data for MySQL, PostgreSQL and MongoDB, so ensure to make a backup first.

* [Backup Mysql](https://devilbox.readthedocs.io/en/latest/maintenance/backup-and-restore-mysql.html)
* [Backup PostgreSQL](https://devilbox.readthedocs.io/en/latest/maintenance/backup-and-restore-pgsql.html)
* [Backup MongoDB](https://devilbox.readthedocs.io/en/latest/maintenance/backup-and-restore-mongo.html)

Once you have backed up everything, start the Devilbox from this branch and import your data.

### Fixes

* Refs: https://github.com/cytopia/devilbox/issues/175
* Refs: https://github.com/cytopia/devilbox/issues/382

### Usage

Stop the Devilbox
```
docker-compose stop
docker-compose rm
```
Update Git and change to the new branch
```
git fetch --all --prune
git checkout docker-volumes
git pull origin docker-volumes
```
**Compare `env-example` with `.env` for changes**

Start the Devilbox
```
docker-compose up
```

### CODE REVIEW

**Comment by fkaminski** [comment]
I can confirm this - branch tested with:

- [x] Tested on Windows ( Docker Toolbox with version [v18.09.0](https://github.com/docker/toolbox/releases/tag/v18.09.0) )

**Comment by mrpsiho** [comment]
Confirm that:

* [ ]  Tested on MacOS (native)

It works for me.

**Comment by cytopia** [comment]
@mrpsiho Thanks for the feedback!

**Comment by cytopia** [comment]
@fkaminski @mrpsiho I've rebased latest `master` into this branch and force-pushed the changes.

**Comment by fkaminski** [comment]
> I've rebased latest master into this branch and force-pushed the changes.

Thanks, now i cannot call phpmyadmin - seems like the #342 issue.
When i change ".devilbox/www/htdocs/vendor/phpmyadmin-4.8/config.inc.php" to readonly again -
then it works ...

**Comment by cytopia** [comment]
> Thanks, now i cannot call phpmyadmin - seems like the #342 issue.
> When i change ".devilbox/www/htdocs/vendor/phpmyadmin-4.8/config.inc.php" to readonly again -
> then it works ...
@fkaminski thanks for the info. I am fixing it and also adding a CI check to ensure this error will never get back into the git repository: https://github.com/cytopia/devilbox/pull/488

**Comment by cytopia** [comment]
Work on Docker Volumes will be prioritized and to ensure backwards compatibility with current users tagged separately on the Release branch, hence v0.x and v1.x will co-exist simultaneously until everything has been furnished.

**Comment by cytopia** [comment]
Use the following branch (which wil also receive tagging): https://github.com/cytopia/devilbox/pull/416

**Pull request merged**
