### PR TITLE
WIP: REL-013 #57 Add RabbitMQ support

### PR DESCRIPTION
**Pull request by cytopia**
## Changelog

* [X] RabbitMQ Container
* [ ] Documentation
* [ ] Intranet layout fixes

### CODE REVIEW

**Comment by science695** [comment]
Have you thought about making the devilbox ui run its server checks more generically (from a yaml file) that users could append new services to?

Example:
Right now to add rabbitmq, you have to add more configuration code, and more code to handle the status checks.

Instead: if all that code was generic and run over every listed service defined in a yaml file, then it would be easier to add custom services (by adding them to this services.yaml and the docker-compose.override.yml)

**Comment by cytopia** [comment]
@science695 FYI: RabbitMQ will be ready in the coming day. I've also added a way to integrate new Docker services fast and easy.

**Comment by cytopia** [comment]
@science695 I've integrated an easier way to have other container available. RabbitMQ is now coming via this PR: https://github.com/cytopia/devilbox/pull/354

I will close this one, but keep the branch for later backporting the intranet settings.

**Comment by cytopia** [comment]
https://devilbox.readthedocs.io/en/latest/custom-container/enable-rabbitmq.html#custom-container-enable-rabbitmq

**Pull request closed without merging**
