### PR TITLE
Release v1.8.1

### PR DESCRIPTION
**Pull request by cytopia**
#### Fixed
- Silence PHP warnings in phpmemcached and opcache GUIs
- [#746](https://github.com/cytopia/devilbox/issues/746) Fix xdebug config for PHP 8.0 and 8.1

#### Added
- Added `check-config.sh` script to check against correct Devilbox configuration

### CODE REVIEW

**Comment by llaville** [comment]
@cytopia Just try to retrieve code from release 1.8.1 and got errors. Just to let you know !

```
llaville@LAPTOP-7JMHIOJJ:~/.devilbox$ git pull origin master
remote: Enumerating objects: 86, done.
remote: Counting objects: 100% (86/86), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 86 (delta 50), reused 72 (delta 45), pack-reused 0
Unpacking objects: 100% (86/86), done.
From https://github.com/cytopia/devilbox
 * branch              master     -> FETCH_HEAD
   87fa92d9..8553a564  master     -> origin/master
Updating 87fa92d9..8553a564
error: unable to create file log/nginx-stable/.keepme: Permission denied
error: unable to create file mod/php-fpm-7.3/.keepme: Permission denied
error: unable to create file mod/php-fpm-7.4/.keepme: Permission denied
error: unable to create file mod/php-fpm-8.0/.keepme: Permission denied
```
and directory with wrong file permissions:
 
```
llaville@LAPTOP-7JMHIOJJ:~/.devilbox$ ll mod/
total 60
drwxr-xr-x 14 llaville llaville 4096 Nov 12 20:17 ./
drwxr-xr-x 18 llaville llaville 4096 Nov 12 20:17 ../
-rw-r--r--  1 llaville llaville   86 Jun  1 18:37 README.md
drwxr-xr-x  2 llaville llaville 4096 Nov 12 20:17 php-fpm-5.2/
drwxr-xr-x  2 llaville llaville 4096 Nov 12 20:17 php-fpm-5.3/
drwxr-xr-x  2 llaville llaville 4096 Jun  1 18:37 php-fpm-5.4/
drwxr-xr-x  2 llaville llaville 4096 Jun  1 18:37 php-fpm-5.5/
drwxr-xr-x  2 llaville llaville 4096 Jun  1 18:37 php-fpm-5.6/
drwxr-xr-x  2 llaville llaville 4096 Jun  1 18:37 php-fpm-7.0/
drwxr-xr-x  2 llaville llaville 4096 Jun  1 18:37 php-fpm-7.1/
drwxr-xr-x  2 llaville llaville 4096 Jun  1 18:37 php-fpm-7.2/
drwxr-xr-x  2 root     root     4096 Jun  1 19:11 php-fpm-7.3/
drwxr-xr-x  2 root     root     4096 Jun 21 11:32 php-fpm-7.4/
drwxr-xr-x  2 root     root     4096 Sep 13 08:35 php-fpm-8.0/
drwxr-xr-x  2 llaville llaville 4096 Nov 12 20:17 php-fpm-8.1/
```

**Comment by cytopia** [comment]
This is due to the wrong file permissions. If you change ownership to `llaville` instead of `root`, it should work

**Comment by llaville** [comment]
Yes , I know but it seems appears only on git pull command. I didn't change the owner or file permissions before

**Comment by cytopia** [comment]
> Yes , I know but it seems appears only on git pull command. I didn't change the owner or file permissions before

The ownership was wrong all along (if you haven't manually added the directories) and this is the fix for it.

**Comment by llaville** [comment]
Another point my feature request about https://github.com/cytopia/devilbox/issues/707

I've put my vhost sources outside the devilbox and got with `check-config.sh` a strange result (part of output)
```
# ==============================================================================
# Checking .env file values
# ==============================================================================
[SUCC] All .env file variables have correct values
[ERR]  Variable 'HOST_PATH_HTTPD_DATADIR' directory does not exist: ~/devilbox_data/www
stat: cannot stat '~/devilbox_data/www': No such file or directory
[ERR]  Variable 'HOST_PATH_HTTPD_DATADIR' directory must be 0755, 0775 or 0777. Has:
stat: cannot stat '~/devilbox_data/www': No such file or directory
```
But it seems ok for me
```
llaville@LAPTOP-7JMHIOJJ:~/.devilbox$ ll ~/devilbox_data/www/
total 60
drwxr-xr-x 15 llaville llaville 4096 Nov  9 15:36 ./
drwxr-xr-x  6 llaville llaville 4096 Jun  4 13:16 ../
drwxr-xr-x 11 llaville llaville 4096 Apr  9  2020 adminlte-bundle-demo/
drwxr-xr-x  9 llaville llaville 4096 Jun  3 08:32 bartlettlabs-sandbox/
drwxr-xr-x 11 llaville llaville 4096 Jun  2 14:20 bartlettlabs-skeleton/
drwxr-xr-x 12 llaville llaville 4096 Jun  4 09:19 bartlettlabs-training/
drwxr-xr-x 11 llaville llaville 4096 Jun  5 12:15 bartlettlabs-website-skeleton/
drwxr-xr-x 13 llaville llaville 4096 Feb 20  2020 carrefour-rdcloyalty/
drwxr-xr-x 17 llaville llaville 4096 Jan 29  2020 carrefour-rdcpayment/
drwxr-xr-x 12 llaville llaville 4096 Jun  6 13:35 devilbox-intranet/
drwxr-xr-x 12 llaville llaville 4096 Apr  9  2020 doctrine-audit-bundle-demo/
drwxr-xr-x 11 llaville llaville 4096 Jun  9 08:28 dvlbox-intranet/
drwxr-xr-x 14 llaville llaville 4096 Feb 11  2020 kimai2/
drwxr-xr-x  8 llaville llaville 4096 Jan 23  2020 rdcvendor/
drwxr-xr-x 15 llaville llaville 4096 Nov  9 11:07 tomasvotruba/
```
In my `.env` i have `HOST_PATH_HTTPD_DATADIR=~/devilbox_data/www`

**Pull request merged**
