### PR TITLE
Add documentation for #222 #229: Custom docker images

### PR DESCRIPTION
**Pull request by cytopia**
# Documentation

Documentation about how to add custom docker images

Thanks to @pedrosanta @mijgame

### CODE REVIEW

**Comment by science695** [comment]
Not a big deal, but the section about duplicating the docker compose file to the docker compose override file is not an ideal solution. I'm looking for a reference page that describes how the docker compose override file is merged that would be helpful.

Maybe this page? it seems like its a bit extra complicated but ....
https://docs.docker.com/compose/extends/

**Comment by pedrosanta** [comment]
**@science695:**
> Not a big deal, but the section about duplicating the docker compose file to the docker compose override file is not an ideal solution.

I'm afraid I don't follow. Could you expand?

> I'm looking for a reference page that describes how the docker compose override file is merged that would be helpful.

Here you go: https://docs.docker.com/compose/extends/#adding-and-overriding-configuration

Yes, this is the _official_ Docker documentation. What I like about this solution is that it's really built-in into Docker and it gives liberty for anyone to extend devilbox at their own preferences _without having to fork the repository and keeping the same upstream state_. Seems a very interesting solution for this.

**Comment by cytopia** [comment]
This has already been included in the last version: http://devilbox.readthedocs.io/en/latest/configuration-files/docker-compose-override-yml.html

Am I missing something?

**Comment by science695** [comment]
I just meant that the documentation doesn't mention that the override file is merged on top of the base docker-compose.yml file.

**Comment by pedrosanta** [comment]
@cytopia No, I don't think so. Documentation is good, includes link to official Docker documentation, all is swell, IMO.

`* Doesn't look like anything to me. *`

**Comment by pedrosanta** [comment]
@science695 It's better to refer to official Docker documentation (like devilbox documentation is doing) in what regards the workings of `docker-compose.override.yml` file as it's something related to Docker. Devilbox documentation on top of that provides two pages with examples on how you can leverage this file.

Going into [Overwrite existing Docker image](http://devilbox.readthedocs.io/en/latest/tutorials/overwrite-existing-docker-image.html#overwrite-existing-docker-image) it states:

```
# How to overwrite a service?

## Generic steps

1. Copy the whole service definition from docker-compose.yml to docker-compose.override.yml
2. Remove anything unnecessary
3. Adjust the values you need
```

With a bit of reading I think it's easy to figure out how the `docker-compose.override.yml` works, IMO. 😉

**Pull request merged**
