### PR TITLE
Devilbox Release v1.0.0

### PR DESCRIPTION
**Pull request by cytopia**
# Devilbox Release v1.0.0

### READFIRST

This branch is constantly being rebased from `master` until final merge, therefore requires **git force pushing**. So how to update changes from this branch:
```bash
# Receive new commits
git fetch --all --prune

# Delete release/v1.0.0 branch
git checkout master
git branch -D release/v1.0.0

# Checkout release/v1.0.0 again
git checkout release/v1.0.0
git pull origin release/v1.0.0
```

Then you will have to ensure to remove container before starting them up again:
```bash
docker-compose stop
docker-compose rm
docker-compose up
```

### IMPORTANT

When using this branch, you will loose all you current data for MySQL, PostgreSQL and MongoDB, so ensure to make a backup first.

* [Backup Mysql](https://devilbox.readthedocs.io/en/latest/maintenance/backup-and-restore-mysql.html)
* [Backup PostgreSQL](https://devilbox.readthedocs.io/en/latest/maintenance/backup-and-restore-pgsql.html)
* [Backup MongoDB](https://devilbox.readthedocs.io/en/latest/maintenance/backup-and-restore-mongo.html)

Once you have backed up everything, start the Devilbox from this branch and import your data.

---

### DOCUMENTATION

Documentation for this release is available here: https://devilbox.readthedocs.io/en/release-v1.0.0/

### DESCRIPTION

This will be the first stable release of the Devilbox.

### Features

**PR's:**

* [x] Docker Volumes: https://github.com/cytopia/devilbox/pull/383
* [ ] ~Internal DNS and Auto DNS separation: https://github.com/cytopia/devilbox/pull/411~: **moved to [Milestone 1.1](https://github.com/cytopia/devilbox/milestone/8)**
* [X] Semantic versioning for faster+safer releases
* [x] Official MySQL, MariaDB and Percona Docker container

**Issues:**

* Refs: https://github.com/cytopia/devilbox/issues/175

### Notable readings

* [CHANGELOG](https://github.com/cytopia/devilbox/blob/a03ac6b63d3103a481a64dd430ceb6c086962b0e/CHANGELOG.md)
* [UPDATING](https://github.com/cytopia/devilbox/blob/a835e7b35629e81dde5c75559c9951d80f52a4a1/UPDATING.md)
* [CONTRIBUTING](https://github.com/cytopia/devilbox/blob/a835e7b35629e81dde5c75559c9951d80f52a4a1/CONTRIBUTING.md)

### CODE REVIEW

**Comment by llaville** [comment]
What a good new ! 
BTW, could you envisage to use this [changelog](https://keepachangelog.com/en/1.0.0/) format

**Comment by vikas5914** [comment]
Hi, I am trying this branch and getting this error: 

```
Recreating devilbox_bind_1 ... error

ERROR: for devilbox_bind_1  Cannot start service bind: driver failed programming external connectivity on endpoint devilbox_bind_1 (0cca32e8f31ea237b52a7257a1d84276f3d3376f1a6ba4f304f3598a418d1eab): Error starting userland proxy: Bind for 0.0.0.0:1050: unexpected error Permission denied

ERROR: for bind  Cannot start service bind: driver failed programming external connectivity on endpoint devilbox_bind_1 (0cca32e8f31ea237b52a7257a1d84276f3d3376f1a6ba4f304f3598a418d1eab): Error starting userland proxy: Bind for 0.0.0.0:1050: unexpected error Permission denied
ERROR: Encountered errors while bringing up the project.
```

I have deleted all the images, container , volumes. 

I have also checked if the port is in used (There are not)

But changing the DNS port to 53 works.

**Comment by cytopia** [comment]
@vikas5914 The DNS container (bind) will listen on both ports, TCP and UDP. Did you ensure that for both protocols there was nothing listening?

**Comment by cytopia** [comment]
The release branch has been tagged with `v1.0.0-alpha` to provide a stable point in time.

**Comment by az09asdf** [comment]
@cytopia 

I tried v1.0.0-alpha1 (ubuntu 18.04 server).

- had to do this (currently I'm not using PostgreSQL)
`#- PGDATA=/var/lib/postgresql/data/pgdata`
to be able to rebuild containers
- also, had to change (nginx)
`image: devilbox/${HTTPD_SERVER}:0.30`
to
`image: devilbox/${HTTPD_SERVER}:0.28`
to be able to access the devilbox site

Otherwise, it seems to be working (MySQL, mongoDB).
(nvm is working too; thank you)

**Comment by cytopia** [comment]
@az09asdf 

1. why do you need to comment the PGDATA directory?
2. Changing http image to `image: devilbox/${HTTPD_SERVER}:0.28` should not be necessary at all

**Comment by vikas5914** [comment]
@cytopia I tried 1050, 1051, 1052 and 1049 ports. Same result. (on 12th Feb)

**Comment by az09asdf** [comment]
@cytopia 

1. tried to reproduce error: now it's gone (false alarm; sorry; cannot remember error message)
2. still the same: change to 0.30 prevents access to the devilbox site (the same for 0.15 version)
(It's probably irrelevant, by I'm using somewhat specific setup: I'm working in Windows (coding, git, browsers) and using devilbox on an ubuntu 18.04 server virtual machine. However, never had such an issue before.)

**Comment by cytopia** [comment]
@az09asdf I have a strong feeling that this might have been related to a Nginx configuration change. Do you get an error like this: `nginx: [emerg] "client_max_body_size" directive is duplicate in /etc/httpd-custom.d/devilbox-custom.conf:1` via Docker logs?

**Comment by cytopia** [comment]
@vikas5914 one thing I can suggest is to fully clean everything:

```bash
# Stop Devilbox and remove its stopped container
docker-compose stop
docker-compose rm -f
# Stop and remove all other container
docker ps -q | xargs docker stop
docker ps -qa | xargs docker rm
```

Then make sure that your `.env` file equals to the new `env-example`.
Also ensure there is for sure nothing else listening on UDP for that port.
And start Devilbox again.

**Comment by az09asdf** [comment]
@cytopia 

Commenting `client_max_body_size` in my custom `nginx.conf` solved the issue.

1.  do you know how to set  `client_max_body_size` for 0.30 ?
2.  couldn't find the error you suggested: "via Docker logs" means `devilbox/log/nginx-stable/` ?

**Comment by cytopia** [comment]
> @cytopia
> 
> Commenting `client_max_body_size` in my custom `nginx.conf` solved the issue.
> 
> 1. do you know how to set  `client_max_body_size` for 0.30 ?
> 2. couldn't find the error you suggested: "via Docker logs" means `devilbox/log/nginx-stable/` ?

Yes you can still overwrite this value if you are on a different context: http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

It currently has been set on the `http` context and you would need the `server` or `location` context to change this value. This can be achieved via custom vhost settings:

* https://devilbox.readthedocs.io/en/latest/vhost-gen/customize-all-virtual-hosts-globally.html#vhost-gen-customize-all-virtual-hosts-globally
* https://devilbox.readthedocs.io/en/latest/vhost-gen/customize-specific-virtual-host.html#vhost-gen-customize-specific-virtual-host

The actual issue that has information on why this was set (to `0` to be in sync with Apache 2.(2|4)) is here:  https://github.com/cytopia/devilbox/issues/356

**Comment by cytopia** [comment]
I will postpone the planned merge until the current issues for Mac and MySQL are investigated.

**Comment by vikas5914** [comment]
@cytopia 

I removed everything (images, volume, network and Devil) and tried again, it worked.

**Comment by cytopia** [comment]
@vikas5914 just in time :-)

The freeze is removed, issue in question (#542) has been resolved

**Pull request merged**
