### PR TITLE
update to phppgadmin-7-12.1

### PR DESCRIPTION
**Pull request by alikon**
# update to phppgadmin-7-12.1

### Goal

update to phppgadmin-7-12.1

solve https://github.com/cytopia/devilbox/issues/728

### DESCRIPTION

 https://github.com/cytopia/devilbox/issues/728

### CODE REVIEW

**Comment by alikon** [comment]
doesn't work when you try to login or with auto-login in config.inc.php

sorry

**Comment by alikon** [comment]
done like in phpmyadmin  regarding DEVILBOX_VENDOR_PHPPGADMIN_AUTOLOGIN

**Comment by cytopia** [comment]
Thanks @alikon I will have a look at this

**Comment by cytopia** [comment]
@alikon thanks for your PR. I've already addressed this now in PR: https://github.com/cytopia/devilbox/pull/742

Additionally I'm also adding documentation on how to update it, so that it works flawlessly with auto-login

**Pull request closed without merging**
